[theme]
primaryColor = "#2C4D82"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FC"
textColor = "#2D3748"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
